Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/welcome_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/welcome_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'


Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Max: 130
